// middleware.ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

// Define the public paths that do NOT require authentication
// Note: These paths correspond to the URLs generated by files in src/app/(auth) and src/app/
const PUBLIC_PATHS = ["/", "/login", "/signup"];
const PROTECTED_REDIRECT_PATH = "/dashboard";

/**
 * Checks if a user is authenticated based on the presence of the session cookie.
 * This is where the cookie logic is explicitly used.
 */
function isAuthenticated(request: NextRequest): boolean {
  // Check for the name of the session cookie set during successful login/signup.
  const sessionCookie = request.cookies.get("freshsaver-session");

  // Return true if the cookie exists and has any value.
  return !!sessionCookie;
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // 1. Normalize path: Removes trailing slash if present (e.g., /dashboard/ -> /dashboard)
  // This is vital for accurate path matching.
  const normalizedPathname =
    pathname.endsWith("/") && pathname.length > 1
      ? pathname.slice(0, -1)
      : pathname;

  const userIsAuthenticated = isAuthenticated(request);

  // 2. Check if the current path is explicitly defined as public
  const isPublicPath = PUBLIC_PATHS.some((path) => path === normalizedPathname);

  // --- Debug Logging (Must appear in your terminal on every request) ---
  console.log(
    `[Middleware Check] Path: ${normalizedPathname} | Auth: ${userIsAuthenticated} | Is Public: ${isPublicPath}`
  );
  // ---------------------------------------------------

  // 3. Logic for Logged-In Users:
  // If authenticated, prevent access to login/signup. Redirect to dashboard.
  if (userIsAuthenticated && isPublicPath) {
    if (normalizedPathname === "/login" || normalizedPathname === "/signup") {
      console.log(
        `[Middleware] Redirecting authenticated user from ${normalizedPathname} to ${PROTECTED_REDIRECT_PATH}.`
      );
      return NextResponse.redirect(
        new URL(PROTECTED_REDIRECT_PATH, request.url)
      );
    }
  }

  // 4. Logic for Logged-Out Users (The core protection rule):
  // If NOT authenticated AND the path is NOT public (e.g., /dashboard, /inventory)
  if (!userIsAuthenticated && !isPublicPath) {
    console.log(
      `[Middleware] Access to protected path ${normalizedPathname} denied. Redirecting to /login.`
    );

    // Store the intended path
    const loginUrl = new URL("/login", request.url);
    loginUrl.searchParams.set("redirect", pathname);
    return NextResponse.redirect(loginUrl);
  }

  // 5. Proceed (e.g., Logged in user accessing /dashboard, or logged out user accessing /)
  return NextResponse.next();
}

// 6. Config: Match all routes except internal/static files.
export const config = {
  matcher: [
    "/((?!api|_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif)$).*)",
  ],
};
